const ex={travel:`Trip confirmation: Your flight to Lisbon leaves Friday, August 16 at 8:40 AM from Terminal 2. Please arrive two hours early. Hotel Aurora check-in is after 3 PM; booking reference AU-8421. Your return flight is Monday, August 19 at 6:15 PM. Remember to bring your passport and book an airport transfer.`,school:`Hello families, a reminder that the Year 5 science fair is next Thursday, September 12. Please send your child's display board to school by Wednesday morning. Families are invited to visit from 2:30–3:30 PM Thursday. Also, the permission slip for the outdoor learning day is due Friday. Thank you!`,bill:`Your electricity statement is ready. Amount due: $184.72 by August 28. This amount is higher than last month because of increased summer usage. Your account is enrolled in AutoPay, but please make sure your payment method ending in 4408 is current. View your usage details online.`};
const plans={travel:{title:'Lisbon trip, ready to go',urgency:'medium',summary:'Your Lisbon travel is confirmed for August 16–19. The key thing to do now is prepare your travel documents and arrange how you’ll get to the airport.',dates:[['AUG 16 · 6:40 AM','Arrive at Terminal 2 for Lisbon flight'],['AUG 16 · 3:00 PM','Hotel Aurora check-in opens'],['AUG 19 · 6:15 PM','Return flight departs']],tasks:[['Check passport validity and pack it','Travel','High','Before Aug 16'],['Book an airport transfer','Travel','Medium','This week'],['Save hotel booking reference AU-8421','Travel','Low','Before departure']],next:'Book your airport transfer now—then your departure day is fully covered.'},school:{title:'Science fair & school forms',urgency:'high',summary:'There are two school deadlines this week: the science-fair display board is due Wednesday morning and the outdoor-learning permission slip is due Friday.',dates:[['SEP 11 · MORNING','Send science-fair display board to school'],['SEP 12 · 2:30 PM','Family science-fair visit'],['SEP 13','Outdoor-learning permission slip due']],tasks:[['Finish and pack the science-fair display board','School','High','Wed, Sep 11'],['Add science-fair visit to family calendar','Calendar','Medium','Thu, Sep 12'],['Sign and return outdoor-learning permission slip','School','High','Fri, Sep 13']],next:'Set out the display board tonight so Wednesday morning stays stress-free.'},bill:{title:'Electricity bill due August 28',urgency:'medium',summary:'Your $184.72 electricity bill will be paid automatically on August 28. Take a moment to verify the linked payment method so AutoPay goes through.',dates:[['AUG 28','AutoPay electricity payment scheduled'],['TODAY','Verify payment method ending in 4408']],tasks:[['Confirm payment method ending in 4408 is current','Finance','High','Before Aug 28'],['Review the online usage breakdown','Finance','Low','When convenient'],['Consider reducing peak summer usage','Home','Low','This month']],next:'Open your utility account and confirm the AutoPay card in under a minute.'}};
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function generic(t){return localOrganizeFree(t);
  const amount=(t.match(/(?:amount due|due)\s*[:\-]?\s*(\$[\d,.]+)/i)||[])[1];
  const due=(t.match(/(?:due|by)\s+([A-Z][a-z]+\s+\d{1,2})/i)||[])[1];
  const card=(t.match(/(?:ending in|ending)\s+(\d{4})/i)||[])[1];
  const autoPay=/auto\s*pay/i.test(t);
  const billLike=/(?:statement|bill|amount due|payment|subscription)/i.test(t);
  if(billLike&&amount){
    const dueLabel=due?due.toUpperCase():'UPCOMING';
    const paymentDetail=autoPay?(card?`AutoPay will charge the payment method ending in ${card}.`:'AutoPay is enabled for this account.'):'A payment needs to be made manually.';
    return{title:'Internet bill, ready to review',urgency:due?'medium':'high',summary:`Your ${amount} internet statement is ready.${due?` Payment is due by ${due}. `:' '}${paymentDetail}`,dates:[[dueLabel,autoPay?'Automatic payment is scheduled':'Payment deadline']],tasks:[[card?`Confirm payment method ending in ${card} is current`:'Confirm the payment method is current','Finance','High',due?`Before ${due}`:'Today'],['Review your internet usage details','Finance','Low','When convenient'],['Save this statement for your records','Finance','Low','This month']],next:autoPay?'Verify the AutoPay method now, then this bill is taken care of.':'Make or schedule the payment now to avoid a missed deadline.'}
  }
  return{title:t.split(/\s+/).slice(0,6).join(' ')+'…',urgency:'medium',summary:'Here’s a clear starting point based on the message you shared. Review the key detail, take the first action, and keep the remaining items visible.',dates:[['NEXT STEP','Review the message and confirm any dates or commitments']],tasks:[['Review the important details','Personal','High','Today'],['Add deadlines to your calendar','Planning','Medium','This week'],['Complete the next required action','Personal','Medium','When ready']],next:'Start with the first task—it is the smallest move that creates clarity.'}
}
function render(d,save=true){$('#loading').classList.add('hidden');$('#composer').classList.add('hidden');let r=$('#results');r.classList.remove('hidden');r.innerHTML=`<div class="result-top"><div><p class="eyebrow">YOUR ACTION PLAN</p><h2>${esc(d.title)}</h2><p>Everything important, made easier to act on.</p></div><span class="urgency ${d.urgency}">${d.urgency} priority</span></div><div class="summary">${esc(d.summary)}</div><div class="grid"><article class="card"><h3>IMPORTANT DATES</h3><ul class="timeline">${d.dates.map(x=>`<li><span class="date">${x[0]}</span><span>${x[1]}</span></li>`).join('')}</ul></article><article class="card"><div class="next"><p>SUGGESTED NEXT STEP</p>${esc(d.next)}</div></article></div><article class="card tasks"><h3>YOUR CHECKLIST</h3><ul class="task-list">${d.tasks.map(x=>`<li class="task"><input class="check" type="checkbox" aria-label="Mark task complete"><div class="task-text"><div class="task-title">${esc(x[0])}</div><div class="task-meta">${x[1]} · ${x[3]}</div></div><span class="priority">${x[2]}</span></li>`).join('')}</ul><div class="export-row"><button id="export" class="export">Copy checklist</button></div></article><div class="export-row"><button id="start-over" class="text-button">← Organize something else</button></div>`;r.querySelectorAll('.check').forEach(x=>x.onchange=()=>x.closest('.task').classList.toggle('done',x.checked));$('#export').onclick=()=>{navigator.clipboard.writeText(d.tasks.map(x=>'[ ] '+x[0]+' — '+x[3]).join('\n'));$('#export').textContent='Copied!';setTimeout(()=>$('#export').textContent='Copy checklist',1200)};$('#start-over').onclick=()=>{r.classList.add('hidden');$('#composer').classList.remove('hidden');$('#message').focus()};if(save){let h=JSON.parse(localStorage.getItem('lifeadmin')||'[]');localStorage.setItem('lifeadmin',JSON.stringify([d,...h.filter(x=>x.title!==d.title)].slice(0,6)));history()}window.scrollTo({top:0,behavior:'smooth'})}
function history(){let h=JSON.parse(localStorage.getItem('lifeadmin')||'[]'),s=$('#recent-section');if(!h.length)return s.classList.add('hidden');s.classList.remove('hidden');$('#recent-list').innerHTML=h.slice(0,3).map((x,i)=>`<button class="recent-item" data-i="${i}"><strong>${esc(x.title)}</strong><span>Reopen action plan · ${x.urgency} priority</span></button>`).join('');document.querySelectorAll('.recent-item').forEach(b=>b.onclick=()=>render(h[b.dataset.i],false))}
document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{$('#message').value=ex[b.dataset.example];$('#message').focus()});$('#organize').onclick=async()=>{let t=$('#message').value.trim();if(!t){$('#error').textContent='Paste a message first, or choose one of the examples above.';return}$('#error').textContent='';$('#composer').classList.add('hidden');$('#loading').classList.remove('hidden');let k=Object.keys(ex).find(x=>ex[x]===t);if(k)return setTimeout(()=>render(plans[k]),650);try{let response=await fetch('/api/organize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:t})});if(response.ok)return render(await response.json());throw new Error('AI service unavailable');}catch(e){render(generic(t));}};$('#message').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')$('#organize').click()};$('#clear-recent').onclick=()=>{localStorage.removeItem('lifeadmin');history()};history();
